# Generated by Django 5.1.4 on 2024-12-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='color',
            field=models.CharField(default='#87CEEB', max_length=7),
            preserve_default=False,
        ),
    ]
