# Generated by Django 5.1.4 on 2025-05-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorios', '0004_priority_user_status_user_alter_reminder_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='priority',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
