# Generated by Django 5.1.4 on 2025-05-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorios', '0005_alter_priority_options_priority_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='status',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
